import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '~/lib/registry';

import GlobalStyles from '~/components/GlobalStyles';
import Header from '~/components/Header';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Business Monitor App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Header />
          {children}
        </StyledComponentsRegistry>
        <GlobalStyles />
      </body>
    </html>
  );
}
