import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '~/lib/registry';

import GlobalStyles from '~/components/GlobalStyles';
import Header from '~/components/Header';
import SignedOutPage from '~/components/SignedOutPage';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Business Monitor App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <StyledComponentsRegistry>
            <Header />
            <SignedOut>
              <SignedOutPage />
            </SignedOut>
            <SignedIn>{children}</SignedIn>
          </StyledComponentsRegistry>
          <GlobalStyles />
        </body>
      </html>
    </ClerkProvider>
  );
}
